# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user_id',
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='Bob', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
